### ISSUE TITLE
Failed to activate the climate-ui package

### ISSUE THREAD

**Issue by geneticgrabbag** [jmcalaway/atom-alphabet-ui#1]
1. Install _climate-ui_ and _climate-syntax_
2. Choose _Climate_ as UI Theme

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [climate-ui](https://github.com/jmcalaway/climate-ui) package, v4.0.0
### Stack Trace

Failed to activate the climate-ui package

```
At fs is not defined

ReferenceError: fs is not defined
    at writeCustomStyles (/Users/epmills/.atom/packages/climate-ui/lib/options.js:133:13)
    at Object.apply (/Users/epmills/.atom/packages/climate-ui/lib/options.js:145:9)
    at Object.activate (/Users/epmills/.atom/packages/climate-ui/lib/climate-ui.js:91:17)
    at ThemePackage.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/theme-package.js:46:28
    at ThemePackage.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/theme-package.js:42:24
    at ThemePackage.module.exports.ThemePackage.activate (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/theme-package.js:38:97)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:332:52
    at /opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/config.js:614:16
    at /opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/themes-panel.js:527:28)
    at /opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/themes-panel.js:534:24
```
### Commands

```
     -5:19.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-atom-dark-syntax.theme-atom-dark-ui)
     -2:31.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "automaticallyUpdate": false,
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "climate-ui",
      "climate-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-dlang, v1.1.2
autocomplete-dcd, v1.7.1
climate-syntax, v4.0.0
climate-ui, v4.0.0
file-icons, v1.7.17
flex-tool-bar, v0.10.2
language-ansible, v0.1.6
language-docker, v1.1.6
linter, v1.11.14
linter-ansible-linting, v1.2.0
linter-ansible-syntax, v1.1.0
linter-docker, v0.1.2
linter-js-standard, v3.4.1
linter-js-yaml, v1.2.5
linter-jsonlint, v1.3.0
minimap, v4.24.7
pdf-view, v0.50.0
tool-bar, v1.0.0

# Dev
No dev packages
```

**Comment by geneticgrabbag** [comment]
Identical behavior attempting to activate _Climate Syntax_

**Comment by jeffcalaway** [comment]
Hey @geneticgrabbag, thank you for downloading Climate. I'll look into this right away. It's curious that you're having the same issue with both themes being that the syntax theme doesn't have any javascript.

Did you try View->Developer->Reload Window? At least for the syntax? Just trying to determine if this is an issue with the theme itself or compatibility issue with the version of your atom or any installed packages.

**Comment by jeffcalaway** [comment]
@geneticgrabbag I just made a small update to options.js. Try again now and let me know how that goes.

**Comment by geneticgrabbag** [comment]
I tried updating but had the same result.  However, reloading the window _did_ clear the error message.

Also, I should clarify that while I did get an error message when loading the syntax, the complaining message was actually generated by the theme.  In either case, both the theme and syntax are now loading error-free.

Thanks for your hard work!

**Comment by jeffcalaway** [comment]
Good! Glad it worked out. Enjoy!
